### PR TITLE
Azure-rm support

### PR DESCRIPTION
**Pull request by mbrehovsky**

### CODE REVIEW

**Comment by jonmort** [comment]
LGTM

**Comment by mattohope** [comment]
+1, lets wait to see what happens with the open fog-azure-rm issues before merging

**Comment by mattohope** [comment]
Jon/Martin, can you please look at my small changes and let me know if you are still happy to merge?

I've been testing this for the last few days and it is working wel

**Comment by jonmort** [comment]
👍

**Pull request merged**
